package neria.tzidkani.jct_contact;

import java.util.ArrayList;

/**
 * Created by Neria Tzidkani on 15/03/2017.
 */

public final class HardCodedList {

    public static ArrayList<Contact> getList(){
        //initialization
        ArrayList<Contact> ContactList =new ArrayList<Contact>();

        //hard coding
        ContactList.add(new Contact("אביעד יערה","aviaday@gmail.com"));
        ContactList.add(new Contact("אגאי אביחי","aviaday@gmail.com"));
        ContactList.add(new Contact("אדד אבישי","avishaya@walla.co.il"));
        ContactList.add(new Contact("אדז'יאשווילי דוד","adjiashv@jct.ac.il"));
        ContactList.add(new Contact("אהרן יצחק","thegingi@gmail.com"));
        ContactList.add(new Contact("אולשנסקי יעקב","aviaday@gmail.com"));
        ContactList.add(new Contact("אוסטפנקו ודים זאב","ostap@math.biu.ac.il"));
        ContactList.add(new Contact("אוסטרובסקי יבגני","ostyav@gmail.com"));
        ContactList.add(new Contact("אופיר נתן","natano@jct.ac.il"));
        ContactList.add(new Contact("אופק יורם","yoramofe@gmail.com"));
        ContactList.add(new Contact("אורבך יהודה","yehudaor@gmail.com"));
        ContactList.add(new Contact("אזולאי רינה","rrinaa@gmail.com"));
        ContactList.add(new Contact("איזק יצחק","isaak@jct.ac.il"));
        ContactList.add(new Contact("איטין יעקב","itin@math.huji.ac.il"));
        ContactList.add(new Contact("אייזנברג אסתריא","estchoc@gmail.com"));
        ContactList.add(new Contact("אייכל רון","ron.eichel@ymail.com"));
        ContactList.add(new Contact("איצקוביץ רז","raziz@mh.shaam.gov.il"));
        ContactList.add(new Contact("אלוש מירב","dmeravall@gmail.com"));
        ContactList.add(new Contact("אלטשולר נתנאל","altshuler@g.jct.ac.il"));
        ContactList.add(new Contact("אליעזר אורן","orene10@gmail.com"));
        ContactList.add(new Contact("אלמוגרבי אמנון","msdolev35@gmail.com"));
        ContactList.add(new Contact("אלן מוריה","ellen@g.jct.ac.il"));
        ContactList.add(new Contact("אלסוונג אבי","aallswang@deloitte.co.il"));
        ContactList.add(new Contact("אמיתי משה","mosh9900@gmail.com"));
        ContactList.add(new Contact("אנגלברג אבא","abba@jct.ac.il"));
        ContactList.add(new Contact("אנגלברג ראובן","ashrei@netvision.net.il"));
        ContactList.add(new Contact("אנגלברג שלמה","shlomoe@jct.ac.il"));
        ContactList.add(new Contact("אסייג אייל","eyalas@013.net.il"));
        ContactList.add(new Contact("אקסלרד חגי","hagai.axelrad@mail.huji.ac.il"));
        ContactList.add(new Contact("ארבל יובל","yuval.arbel@gmail.com"));
        ContactList.add(new Contact("אריאלי יואל","arieli@jct.ac.il"));
        ContactList.add(new Contact("ארן נתי","natiaron.huji@gmail.com"));
        ContactList.add(new Contact("בבצ'נקו אנטולי","babchenk@jct.ac.il"));
        ContactList.add(new Contact("בגנו אלי","bagnoe@jct.ac.il"));
        ContactList.add(new Contact("בדיחי יהודה","badihi@jct.ac.il"));
        ContactList.add(new Contact("בוכניק דן","bouhnik@jct.ac.il"));
        ContactList.add(new Contact("ביצ'ק שלמה","beychok@jct.ac.il"));
        ContactList.add(new Contact("בירפר איליה","birfer@g.jct.ac.il"));
        ContactList.add(new Contact("בכר רחל","rharris@jct.ac.il"));
        ContactList.add(new Contact("בל נח","bell@jct.ac.il"));
        ContactList.add(new Contact("בלאונשטיין נתן","nathan.blaunstein@hotmail.com"));
        ContactList.add(new Contact("בלונדהיים דני","d@danyb.co.il"));
        ContactList.add(new Contact("בן גל רונן","ronenbengal@gmail.com"));
        ContactList.add(new Contact("בן דוב אביגדור","a.bendov@yahoo.com"));
        ContactList.add(new Contact("בן נון אסף","Assafb100@walla.com"));
        ContactList.add(new Contact("בן עזרא דוד","benezra@g.jct.ac.il"));
        ContactList.add(new Contact("בן שור -פליישמן דוב אברהם (בריאן)","hdvash@gmail.com"));
        ContactList.add(new Contact("בנק מיכאל","bankmichael1@gmail.com"));

        String tempname23487= "בנש\"ק - דוקוב אלישבע";
        ContactList.add(new Contact(tempname23487,"le7.bonchek.dokow@gmail.com"));
        ContactList.add(new Contact("בר-אל רונן","barel306@gmail.com"));
        ContactList.add(new Contact("בר (קנול) דבורה","dvorahk31@gmail.com"));
        ContactList.add(new Contact("בר יהודה","yehudab123@gmail.com"));
        ContactList.add(new Contact("ברוס יוחנן","Yochy.bruce@gmail.com"));
        ContactList.add(new Contact("ברוס נחמן","nachmanbruce@gmail.com"));
        ContactList.add(new Contact("ברוקמן לאון","lbruckman@iplight.com"));
        ContactList.add(new Contact("ברזילי דניאל","Daniel.Barz@gmail.com"));
        ContactList.add(new Contact("ברזילי יעקב","ybarzila@g.jct.ac.il"));
        ContactList.add(new Contact("בריטברד אורי","orib@jct.ac.il"));
        ContactList.add(new Contact("ברכץ דידיה","barkatz@jct.ac.il"));
        ContactList.add(new Contact("ברלב בן- ציון","bbarlev@jct.ac.il"));
        ContactList.add(new Contact("ברנט- יצחקי זהר","zohari@gmail.com"));
        ContactList.add(new Contact("ברנר חיים","cbraner@gmail.com"));
        ContactList.add(new Contact("ברנשטיין אלברטו","albertob62@gmail.com"));
        ContactList.add(new Contact("ברפמן עידו","idolm@walla.co.il"));
        ContactList.add(new Contact("ברק רונן","ronen.barak@biu.ac.il"));
        ContactList.add(new Contact("בש הלל","hillel.basch@biu.ac.il"));
        ContactList.add(new Contact("גולדברג בני","beni4963@gmail.com"));
        ContactList.add(new Contact("גולדברג יעקב","yaakovgol@gmail.com"));
        ContactList.add(new Contact("גולדברג מרים","miriam_gberg@yahoo.com"));
        ContactList.add(new Contact("גולדיטש הילה","orgatz@gmail.com"));
        ContactList.add(new Contact("גולדנברג מאיר","mgoldenbe@gmail.com"));
        ContactList.add(new Contact("גולדשטיין יאיר","ygoldsht@jct.ac.il"));
        ContactList.add(new Contact("גולדשטיין משה","goldmosh@jct.ac.il"));
        ContactList.add(new Contact("גולובצ'יוב יוסף יצחק","yosi_habad@yahoo.com"));
        ContactList.add(new Contact("גולנדר לריסה","laragolender@gmail.com"));
        ContactList.add(new Contact("גורדון אלישבע","gordon@g.jct.ac.il"));
        ContactList.add(new Contact("גורדין הראל","harelgo@gmail.com"));
        ContactList.add(new Contact("גיאת יהל","yahel@g.jct.ac.il"));
        ContactList.add(new Contact("גילאון דרור","gilond@gmail.com"));
        ContactList.add(new Contact("גלבוע אורי","urig@g.jct.ac.il"));
        ContactList.add(new Contact("גלמן דוד","DGELMAN@BEZEQINT.NET"));
        ContactList.add(new Contact("גלנט ראובן","rgallant@g.jct.ac.il"));
        ContactList.add(new Contact("גנוט שרה","sarag@jct.ac.il"));
        ContactList.add(new Contact("גנון מרדכי","ganon@jct.ac.il"));
        ContactList.add(new Contact("גנסבורגר אליעזר","eliezer@g.jct.ac.il"));
        ContactList.add(new Contact("גסנבאור רבקה","rivkagas@walla.co.il"));
        ContactList.add(new Contact("גפן סימון","simgef@gmail.com"));
        ContactList.add(new Contact("גרדוול גדעון","gidi.gradwohl@gmail.com"));
        ContactList.add(new Contact("גרינברג אליהו","eligr1@bezeqint.net"));
        ContactList.add(new Contact("גרינברג נורית","nurit@jct.ac.il"));
        ContactList.add(new Contact("גרינברג שרה","saragr.cpa@gmail.com"));
        ContactList.add(new Contact("גרינברג תומר","tomerigo@gmail.com"));
        ContactList.add(new Contact("גרסטל צבי - אנריקה","enrique.gerstl@mail.huji.ac.il"));
        ContactList.add(new Contact("גרסטנפלד רון","rongerstenfeld@gmail.com"));
        ContactList.add(new Contact("גת יוחאי","yochaigat@gmail.com"));
        ContactList.add(new Contact("גת עפר","ofergat40@gmail.com"));
        ContactList.add(new Contact("דהאן איתן","dahan.eyt@gmail.com "));
        ContactList.add(new Contact("דובדבני רננה","yrduvdev@gmail.com"));
        ContactList.add(new Contact("דוד אייבור","ivordvd@gmail.com"));
        ContactList.add(new Contact("דוד אסתר","astrdod@acad.ash-college.ac.il"));
        ContactList.add(new Contact("דוד מרסלו מרטין","marcelod@g.jct.ac.il"));
        ContactList.add(new Contact("דחוביץ' בוריס","borisbmd@gmail.com"));
        ContactList.add(new Contact("דיין דוד","dayandav@g.jct.ac.il"));
        ContactList.add(new Contact("דיכובסקי חנה","chana.dichovsky@gmail.com"));
        ContactList.add(new Contact("דנא-פיקארד טיירי","ndp@jct.ac.il"));
        ContactList.add(new Contact("דנציג נחום","danzig@jct.ac.il"));
        ContactList.add(new Contact("דשט עזרא","ezradashtt@gmail.com"));
        ContactList.add(new Contact("הדד שלמה","shlomo@jct.ac.il"));
        ContactList.add(new Contact("הוכברג קנת","rector@jct.ac.il"));
        ContactList.add(new Contact("הוכמן רעות","reuthochman@walla.com"));
        ContactList.add(new Contact("הומפריס מיכאל","humphries@bezeqint.net"));
        ContactList.add(new Contact("הופמן יורי","gofman@jct.ac.il"));
        ContactList.add(new Contact("הופמן רג'ין","reginelustig@gmail.com"));
        ContactList.add(new Contact("הוצלר דורית","hutzler@jct.ac.il"));
        ContactList.add(new Contact("היומן עזריאל","heuman@jct.ac.il"));
        ContactList.add(new Contact("הירש תהילה","baltehila@gmail.com"));
        ContactList.add(new Contact("הכהן-קרנר יעקב","kerner@jct.ac.il"));
        ContactList.add(new Contact("הכהן עודד","ohacohen@zahav.net.il"));
        ContactList.add(new Contact("הלפרין ליבי","taibale@gmail.com"));
        ContactList.add(new Contact("הנל אריה שלמה","arie.haenel@jct.ac.il"));
        ContactList.add(new Contact("הרוניאן דן","dharonian@gmail.com"));
        ContactList.add(new Contact("הרסט צבי","tsvikah@013.net"));
        ContactList.add(new Contact("הרסט תרצה","tirza.hirst@gmail.com"));
        ContactList.add(new Contact("ואקנין חיה","anais_vak@hotmail.fr"));
        ContactList.add(new Contact("ווגל ג'ויס","vogel_joyce@hotmail.com"));
        ContactList.add(new Contact("וולדנברג אלמוג","almogwoldenberg@gmail.com"));
        ContactList.add(new Contact("ויזן אריה","aryehwiesen@gmail.com"));
        ContactList.add(new Contact("וייס שמעון","weissa@jct.ac.il"));
        ContactList.add(new Contact("וינמן שמואל","weinman@jct.ac.il"));
        ContactList.add(new Contact("וינר שלומי","shlomy.wiener@mail.huji.ac.il"));
        ContactList.add(new Contact("וינשטוק דן","danweinstock1969@gmail.com"));
        ContactList.add(new Contact("ויסמן אפרים","efy.wei@gmail.com"));
        ContactList.add(new Contact("ולנסי - טובלי מרים","miryam.tobaly@mail.huji.ac.il"));
        ContactList.add(new Contact("ולצמן יריב","welzmany@biu.ac.il"));
        ContactList.add(new Contact("ונונו ריקה","rika.vanunu@gmail.com"));
        ContactList.add(new Contact("ורשבסקי יעקב","jacobw@bezeqint.net"));
        ContactList.add(new Contact("זגורי יוסף","yossi@itc.co.il"));
        ContactList.add(new Contact("זייטון דוד","ed.technologie@gmail.com"));
        ContactList.add(new Contact("זילביגר אבי","silbiger@jct.ac.il"));
        ContactList.add(new Contact("זילברמן אבירם","aviramz@jct.ac.il"));
        ContactList.add(new Contact("זילברשטיין דן","dzilbers@g.jct.ac.il"));
        ContactList.add(new Contact("זילברשטיין עמית","amitzilber@gmail.com"));
        ContactList.add(new Contact("זימון יאיר","Yair_zimon@hotmail.com"));
        ContactList.add(new Contact("חבצלת מיכל","michalhava@gmail.com"));
        ContactList.add(new Contact("חדאד יורם","haddad@jct.ac.il"));
        ContactList.add(new Contact("חדד אורטל","ortal.haddad@gmail.com"));
        ContactList.add(new Contact("חזקלוביץ ישראל","jch1826@gmail.com"));
        ContactList.add(new Contact("חיון לאה","lea.hayun1@gmail.com"));
        ContactList.add(new Contact("חיותין לאוניד","leonid@jct.ac.il"));
        ContactList.add(new Contact("חייט אלכסנדר","khait@vms.huji.ac.il"));
        ContactList.add(new Contact("חלמסקי אנה","anna.khalemsky@gmail.com"));
        ContactList.add(new Contact("חלמסקי מיכאל","khalemsky@gmail.com"));
        ContactList.add(new Contact("חפץ אליהו","heifetz@g.jct.ac.il"));
        ContactList.add(new Contact("טובול יוסף","tobol@jct.ac.il"));
        ContactList.add(new Contact("טיטון מרים","mt.mahontal@gmail.com"));
        ContactList.add(new Contact("טייטלבאום אריה","A_hay@jct.ac.il"));
        ContactList.add(new Contact("טישלר הדס","hadassc@gmail.com"));
        ContactList.add(new Contact("טליס ודים","talisv@yahoo.com"));
        ContactList.add(new Contact("טרבלסי מאור","trabelsy@g.jct.ac.il"));
        ContactList.add(new Contact("טרייסטמן אברהם","treistma@jct.ac.il"));
        ContactList.add(new Contact("יוגב מיכל","michal.yogev@biu.ac.il"));
        ContactList.add(new Contact("יושעי אסף","ayoshi@g.jct.ac.il"));
        ContactList.add(new Contact("יחזקאל גיא","joohie@gmail.com"));
        ContactList.add(new Contact("יפרח ישראל","yisrael_i@walla.co.il"));
        ContactList.add(new Contact("יצחקי מור","moratias100@walla.com"));
        ContactList.add(new Contact("ירון יוסי","yossiyn@yahoo.com"));
        ContactList.add(new Contact("ירמולין יבגני","yevgeny_ye@yahoo.com"));
        ContactList.add(new Contact("ישועה טליה","tyeshua@gmail.com"));
        ContactList.add(new Contact("ישראלי יניב","yanivi@jct.ac.il"));
        ContactList.add(new Contact("כהן אושרי","mail.oshri@gmail.com"));
        ContactList.add(new Contact("כהן דוד","cdavid@g.jct.ac.il"));
        ContactList.add(new Contact("כהן דניאל","cohen0073@gmail.com"));
        ContactList.add(new Contact("כהן חיה","chayaco@hotmail.com"));
        ContactList.add(new Contact("כהן יניב","6210203@gmail.com"));
        ContactList.add(new Contact("כהן מיכל","mikhalc@gmail.com"));
        ContactList.add(new Contact("כהן רן","ran464@inter.net.il"));
        ContactList.add(new Contact("כהן שושנה","shoshi1991@gmail.com"));
        ContactList.add(new Contact("כהן שרה","sarahc2401@gmail.com"));
        ContactList.add(new Contact("כמון פאול דוד","paulk@g.jct.ac.il"));
        ContactList.add(new Contact("כספי אבי (אברהם יצחק","avi.caspi@gmail.com"));
        ContactList.add(new Contact("כץ רונית","ronchit@gmail.com"));
        ContactList.add(new Contact("כרמי גולן","carmi@jct.ac.il"));
        ContactList.add(new Contact("לאונארונס ברוך","b_lionarons@yahoo.co.uk"));
        ContactList.add(new Contact("לב יאיר","YAIRLEV84@GMAIL.COM"));
        ContactList.add(new Contact("לוי-נוימנד אדית","edithln@017.net.il"));
        ContactList.add(new Contact("לוי-פרזון הדס","hnlevi@gmail.com"));
        ContactList.add(new Contact("לוי אלישיב","elil@jct.ac.il"));
        ContactList.add(new Contact("לוי אריה","arielevy@actcom.net.il"));
        ContactList.add(new Contact("לוי מאיר","Meirlevy11@hotmail.com"));
        ContactList.add(new Contact("לוי שמשון","levy_sh@hit.ac.il"));
        ContactList.add(new Contact("לויאן יהונתן","levian@g.jct.ac.il"));
        ContactList.add(new Contact("לוין אורי","orilevin8@gmail.com"));
        ContactList.add(new Contact("לוין ישראל","yslevine@yahoo.com"));
        ContactList.add(new Contact("לוין לביאה","livialevine@gmail.com"));
        ContactList.add(new Contact("לחמן איתמר","itamar.lachman@gmail.com"));
        ContactList.add(new Contact("ליבסקינד חיה","liebchaya@gmail.com"));
        ContactList.add(new Contact("לייכטר יצחק","leichter@jct.ac.il"));
        ContactList.add(new Contact("ליסיצין שרית","slicitzin@gmail.com"));
        ContactList.add(new Contact("לירצמן ולדיסלב יוסף","lirtsman@phys.huji.ac.il"));
        ContactList.add(new Contact("לנדר ולדימיר","vblender50@yahoo.com"));
        ContactList.add(new Contact("לפיד דוד","lapid02@gmail.com"));
        ContactList.add(new Contact("לרנר שמעון","shimon.lerner@mail.huji.ac.il"));
        ContactList.add(new Contact("מאיר אשר","ameir@jct.ac.il"));
        ContactList.add(new Contact("מדר מני","menimadar@gmail.com"));
        ContactList.add(new Contact("מוגהץ דרור","myghaz@yahoo.com"));
        ContactList.add(new Contact("מזרחי שמעון","shimon@jct.ac.il"));
        ContactList.add(new Contact("מט ברכה","bracha.meth@gmail.com"));
        ContactList.add(new Contact("מי-טל עמי","amimeytal@gmail.com"));
        ContactList.add(new Contact("מילגרום בנימין","milgromb@gmail.com"));
        ContactList.add(new Contact("מילסטון עדינה","milston@g.jct.ac.il"));
        ContactList.add(new Contact("מימון טל","talmaimon3@gmail.com"));
        ContactList.add(new Contact("מינס אחיעד","ahiad8@gmail.com"));
        ContactList.add(new Contact("מישקין יונתן","jonathanmishkin@gmail.com"));
        ContactList.add(new Contact("מנדלבאום יעקב","yaaqovm@gmail.com"));
        ContactList.add(new Contact("מנדלבאום פנחס","pinchasm@jce.ac.il"));
        ContactList.add(new Contact("מנור משה","mm1306@gmail.com"));
        ContactList.add(new Contact("מנס ערן","msemanes@gmail.com"));
        ContactList.add(new Contact("מעיין יפית","yafit.maayan@gmail.com"));
        ContactList.add(new Contact("מעלם בני","bennyme73@gmail.com"));
        ContactList.add(new Contact("מרירס עדן","eden.jct@gmail.com"));
        ContactList.add(new Contact("נאמן ויקטור","neeman@jct.ac.il"));
        ContactList.add(new Contact("נאמן רחל","r7979@bezeqint.net"));
        ContactList.add(new Contact("נדל אברהם","avraham.nadell@gmail.com"));
        ContactList.add(new Contact("נדלר חנה","hanninadler@gmail.com"));
        ContactList.add(new Contact("נוביק אירית","nowik@jct.ac.il"));
        ContactList.add(new Contact("נוביק מרדכי","motinovick@gmail.com"));
        ContactList.add(new Contact("נווה אופיר","naveof@cs.bgu.ac.il"));
        ContactList.add(new Contact("נוימן גילה","gilaneu@gmail.com"));
        ContactList.add(new Contact("נורין אברהם","harbashan@gmail.com"));
        ContactList.add(new Contact("נח אלדד","eldad@mnktax.co.il"));
        ContactList.add(new Contact("נח סלמן","salman@jct.ac.il"));
        ContactList.add(new Contact("ניימן אהרן","naiman@jct.ac.il"));
        ContactList.add(new Contact("ניימן אוריאל","urielnayman@gmail.com"));
        ContactList.add(new Contact("ניימן פנחס","pinchasn@jct.ac.il"));
        ContactList.add(new Contact("ניימן צבי שמואל","zvi.shmuel@gmail.com"));
        ContactList.add(new Contact("ניצן שרון","nitzan4788@neto.net.il"));
        ContactList.add(new Contact("ניר אסנת","osnat.notea@gmail.com"));
        ContactList.add(new Contact("נתנזון אלכסנדר","anatanzon@012.net.il"));
        ContactList.add(new Contact("סגל אביטל","orlin.avital@gmail.com"));
        ContactList.add(new Contact("סגל שי יהודה","segals@g.jct.ac.il"));
        ContactList.add(new Contact("סגרון רות","ruthishilman@gmail.com"));
        ContactList.add(new Contact("סויסה שמעון","shimon.suissa@gmail.com"));
        ContactList.add(new Contact("סולומונס אברהם","avrhmsol@jct.ac.il"));
        ContactList.add(new Contact("סופייב הדר","hadarch@g.jct.ac.il"));
        ContactList.add(new Contact("סוקולובר גלעד","soko6@walla.com"));
        ContactList.add(new Contact("סטנדר רות","ruthcynthia@gmail.com"));
        ContactList.add(new Contact("סיגרון מוריה","moria.sigron@mail.huji.ac.il"));
        ContactList.add(new Contact("סיני אפרים","ephraims_cpa@bezeqint.net"));
        ContactList.add(new Contact("סלוצקי אהרון","aaron.slutsky@gmail.com"));
        ContactList.add(new Contact("סמית ישראל","yisyaqs@gmail.com"));
        ContactList.add(new Contact("סמקובסקי איגור","smakovsky.igor@gmail.com"));
        ContactList.add(new Contact("סנדלר עוזיאל","sandler@jct.ac.il"));
        ContactList.add(new Contact("סנדרוביץ חנוך","hsenderowitz@gmail.com"));
        ContactList.add(new Contact("סספורטס דבורה","sandebsas@gmail.com"));
        ContactList.add(new Contact("סעדון גיא","guysaadon8@gmail.com"));
        ContactList.add(new Contact("סקאר צבי","scarr@g.jct.ac.il"));
        ContactList.add(new Contact("עאפרת","efrati.amar@gmail.com"));
        ContactList.add(new Contact("עברי יואח","yoachi@zahav.net.il"));
        ContactList.add(new Contact("עדי מרים","adi1miriam@gmail.com"));
        ContactList.add(new Contact("עדס אסתי","estibb8@gmail.com"));
        ContactList.add(new Contact("עוזרי אודליה","odelyao@jct.ac.il"));
        ContactList.add(new Contact("עזרא צור אלישי","elishai85@gmail.com"));
        ContactList.add(new Contact("עמרדכי","bushido1974@yahoo.com"));
        ContactList.add(new Contact("פאלק ראובן","reuvenf10@yahoo.com"));
        ContactList.add(new Contact("פאר אלי","Elip@shap.co.il"));
        ContactList.add(new Contact("פוזנר מרדכי","posner@jct.ac.il"));
        ContactList.add(new Contact("פולין אברהם (בריאן)","polin@jct.ac.il"));
        ContactList.add(new Contact("פז נעם","6210345@gmail.com"));
        ContactList.add(new Contact("פטל הרצל","patal@jct.ac.il"));
        ContactList.add(new Contact("פטרון עמיקם","amikamp@yahoo.com"));
        ContactList.add(new Contact("פיאטקובסקי יואב","pjoav@zahav.net.il"));
        ContactList.add(new Contact("פיוטרקובסקי מנשה","puterkov@gmail.com"));
        ContactList.add(new Contact("פינטו משה","moshepintocpa@gmail.com"));
        ContactList.add(new Contact("פיש מנחם","mafc99@gmail.com"));
        ContactList.add(new Contact("פרדג' אריק","erick.fredj@gmail.com"));
        ContactList.add(new Contact("פרוכטמן אמונה","emuna@jct.ac.il"));
        ContactList.add(new Contact("פרטוש אלי","epartuch@zahav.net.il"));
        ContactList.add(new Contact("פרידמן אבי","avi@afriedmanlaw.co.il"));
        ContactList.add(new Contact("פרידמן זאב יהודה","frzeev@gmail.com"));
        ContactList.add(new Contact("פרידמן יעקב","friedman@jct.ac.il"));
        ContactList.add(new Contact("פרינתה חיים","haimpa@gmail.com"));
        ContactList.add(new Contact("פרישמן יבגני","evgeni@jct.ac.il"));
        ContactList.add(new Contact("פרץ יוסף","yosip@jct.ac.il"));
        ContactList.add(new Contact("צ'סרקס כתריאל","lev.katriel@gmail.com"));
        ContactList.add(new Contact("צ'רניאק מיכאל","cherniak@jct.ac.il"));
        ContactList.add(new Contact("צאהן נחמה","zahn@g.jct.ac.il"));
        ContactList.add(new Contact("צבע רבקה","rtseva@neto.bezeqint.net"));
        ContactList.add(new Contact("צוקרמן אריה","newarieh@gmail.com"));
        ContactList.add(new Contact("קאופמן דוד","davidk1970@gmail.com"));
        ContactList.add(new Contact("קדם יונתן","kedem.online@gmail.com"));
        ContactList.add(new Contact("קדרון איבי","ivy@jct.ac.il"));
        ContactList.add(new Contact("קדרון דוד","dav.kidron@gmail.com"));
        ContactList.add(new Contact("קוטלר ציקי","tzikiko@gmail.com"));
        ContactList.add(new Contact("קוך יהושוע אוליביה","koch@jct.ac.il"));
        ContactList.add(new Contact("קומאיר","komar@jct.ac.il"));
        ContactList.add(new Contact("קונלי אהוד","ehud.conley@gmail.com"));
        ContactList.add(new Contact("קופליק אלישבע","skuflik@gmail.com"));
        ContactList.add(new Contact("קופר ג'רלד","cooper@jce.ac.il"));
        ContactList.add(new Contact("קופרמן כלילה","klilacop@hotmail.com"));
        ContactList.add(new Contact("קופרשמידט שלומי","hrshelomi@clalit.org.il"));
        ContactList.add(new Contact("קורוב שולמית","korob@g.jct.ac.il"));
        ContactList.add(new Contact("קורח-שריקי ורד","veredksh@gmail.com"));
        ContactList.add(new Contact("קורח אריאל","korach@neto.net.il"));
        ContactList.add(new Contact("קיוול עדית","kivel@g.jct.ac.il"));
        ContactList.add(new Contact("קיי אביגדור","kay@jct.ac.il"));
        ContactList.add(new Contact("קליין אלכסנדר","kleina@g.jct.ac.il"));
        ContactList.add(new Contact("קליין רחל","rahel@g.jct.ac.il"));
        ContactList.add(new Contact("קלמן גיא","guykelman@gmail.com"));
        ContactList.add(new Contact("קמיל ישראל","kamil2is@gmail.com"));
        ContactList.add(new Contact("קפלן טומס","tomc@cbs.gov.il"));
        ContactList.add(new Contact("קצב יצחק","yitzik@g.jct.ac.il"));
        ContactList.add(new Contact("קר פרידמן רבקה חוה","rivka.chava.friedman@gmail.com"));
        ContactList.add(new Contact("קרבצ'יק משה","kravchik@g.jct.ac.il"));
        ContactList.add(new Contact("קריהודית","judkrame@netvision.net.il"));
        ContactList.add(new Contact("קרסנטי אבי","karsenty@g.jct.ac.il"));
        ContactList.add(new Contact("רבן רן","ran8@netvision.net.il"));
        ContactList.add(new Contact("רוזן ישראל","rozzen@umtb.co.il"));
        ContactList.add(new Contact("רוזנבליט אורית","rozority@gmail.com"));
        ContactList.add(new Contact("רוזנגרטן אורה","rosengarten@szwc.org.il"));
        ContactList.add(new Contact("רוזנפלד אבי","rosenfa@gmail.com"));
        ContactList.add(new Contact("רוטשטיין אלכסנדר","rot@jct.ac.il"));
        ContactList.add(new Contact("רוכלין אלימלך","elirochlin8@gmail.com"));
        ContactList.add(new Contact("ריזמוביץ תמר","tamaraz1992@gmail.com"));
        ContactList.add(new Contact("רייסין עמנואל","resin@g.jct.ac.il"));
        ContactList.add(new Contact("רייף מרדכי","moti@jct.ac.il"));
        ContactList.add(new Contact("ריכרדסון אריאלה","ariellarich@gmail.com"));
        ContactList.add(new Contact("רכס שולמית","shulamit.reches@gmail.com"));
        ContactList.add(new Contact("שאקי אחיעזר","shakia100@gmail.com"));
        ContactList.add(new Contact("שאקי יאיר","y_shaki@hotmail.com"));
        ContactList.add(new Contact("שגב רות","rsegev@g.jct.ac.il"));
        ContactList.add(new Contact("שוורץ בוריס","shwartzt_b@bezeqint.net"));
        ContactList.add(new Contact("שוורץ ביאטה","beata.itina@gmail.com"));
        ContactList.add(new Contact("שוייצר חיה","chayash10@gmail.com"));
        ContactList.add(new Contact("שוייצר נדב","nadavsh1@gmail.com"));
        ContactList.add(new Contact("שוקרון שמואל","Schocron@g.jct.ac.il"));
        ContactList.add(new Contact("שורץ אריאל","magen_dan@yahoo.com"));
        ContactList.add(new Contact("שחור שירה","shirashachor10@walla.com"));
        ContactList.add(new Contact("שטולמן אלן","alan@jct.ac.il"));
        ContactList.add(new Contact("שטולמן אריאל","stulman@jct.ac.il"));
        ContactList.add(new Contact("שטיינר הלל","hillel.cpa@gmail.com"));
        ContactList.add(new Contact("שטינמץ נתן","nati.steinmetz@gmail.com"));
        ContactList.add(new Contact("שטראוס טליה","taliastraus@gmail.com"));
        ContactList.add(new Contact("שטרו אורי","stroh@jct.ac.il"));
        ContactList.add(new Contact("שטרן שירה","shirastn@gmail.com"));
        ContactList.add(new Contact("שטרנברג אורי","uri.ste@gmail.com"));
        ContactList.add(new Contact("שכטר יובל","schyuval@gmail.com"));
        ContactList.add(new Contact("שלקמן פיונה","fionashlakman4@gmail.com"));
        ContactList.add(new Contact("שנדוביץ חיים יוסף","chysch@gmail.com"));
        ContactList.add(new Contact("שניטמן תמר","tamarshnitman@gmail.com"));
        ContactList.add(new Contact("שנפס דניאלה","shnaps@jct.ac.il"));
        ContactList.add(new Contact("שנפס יהודה","yehuds@gmail.com"));
        ContactList.add(new Contact("שנרב תמר","shnerb@gmail.com"));
        ContactList.add(new Contact("שקרון מרב","meravgu@gmail.com"));
        ContactList.add(new Contact("תקוע גלעד","giladtk@mh.shaam.gov.il"));


        // returning hard coded list
        return ContactList;
    }
}
